### ISSUE TITLE
Создание проекта

### ISSUE THREAD

**Issue by ledmitr** [ledmitr/online-galasavalcka#1]
Создать проект maven

**Comment by dmirosh** [comment]
Предлагаю не извращаться и использовать нейтивный для скалы скалы sbt

**Comment by dmirosh** [comment]
Запушил сервер. запуск sbt run
достпуен по http://localhost:8081/

​[1:14] 
В качестве дефолтной страницы отдается resources -> index.html
Статичекий контент доступен по префиксу static.
Смотри  как сейчас подключаются main.css и main.js
