### ISSUE TITLE
frontend

### ISSUE THREAD

**Issue by ledmitr** [ledmitr/online-galasavalcka#4]
Выбрать технологии, которые будут исполоьзоваться для разработки фронтенда

**Comment by tar** [comment]
1) JQuery 2.4+
2) Boostrap 3+
3) Please choose free boostrap theme in https://bootswatch.com/
4) select2 for dropdowns
5) c3js for chars

**Comment by ledmitr** [comment]
Мне нравится тема
https://bootswatch.com/united/

**Comment by tar** [comment]
Ok! got it.

also we will use angularJS as main framework and ejs templates.
